name: Auto Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Verify Build Output
      run: |
        echo "Checking build output..."
        ls -la dist/
        echo "Total files in dist: $(find dist -type f | wc -l)"

    - name: Deploy to Public Repository
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        TARGET_REPO: unblcked-gg-games/unblcked-gg-games.github.io
      run: |
        # Check if token exists
        if [ -z "$DEPLOY_TOKEN" ]; then
          echo "❌ ERROR: DEPLOY_TOKEN secret is not set!"
          echo "Please add DEPLOY_TOKEN to repository secrets."
          exit 1
        fi
        
        # Navigate to build directory
        cd dist
        
        # Initialize git repository
        git init
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'
        
        # Add all files
        git add .
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to deploy"
          exit 0
        fi
        
        # Commit changes
        git commit -m "🚀 Auto-deploy from source repo - $(date '+%Y-%m-%d %H:%M:%S')"
        
        # Add remote with token authentication
        git remote add origin https://x-access-token:${DEPLOY_TOKEN}@github.com/${TARGET_REPO}.git
        
        # Create and switch to main branch
        git branch -M main
        
        # Push to public repository
        echo "Deploying to ${TARGET_REPO}..."
        git push -f origin main
        
        echo "✅ Deployment successful!" 